workflows:
  ios-build:
    name: iOS build
    max_build_duration: 60 # Tempo máximo de execução (em minutos)
    instance_type: mac_mini
    platform: ios
    ios:
      build:
        flutter: stable
        cache:
          restore: true # Usar cache para dependências Flutter, se já existirem
        config:
          build_name: 1.0.0
          build_number: 1
        # Comando para rodar o build no iOS
        flutter_build:
          build_mode: release
          target: lib/main.dart
      # Gerar o arquivo IPA
      artifacts:
        - build/ios/ipa/*.ipa
      # Se você quiser usar testes unitários ou integrados, configure aqui.
      # Isso é opcional
      test:
        - flutter test
