workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60 # Tempo máximo de execução (em minutos)
    instance_type: mac_mini_m1   # Escolha um tipo de instância válido
    environment:
      flutter: stable
    scripts:
      - name: Flutter Build
        script: |
          flutter pub get
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa
